- src/Transmogrification.cpp
Item IDs specified directly via option "Transmogrification.Allowed" are allowed for transmogrification without restriction.
Closes #17
> feat: allow item IDs without restriction

- CMakeLists.txt
- src/transmog_scripts.cpp
Currently if using both mod-transmog and mod-weapon-visual this can result in weapon visuals not shown, because both modules use "OnLogin" to apply their visual modifications.
With commit https://github.com/azerothcore/azerothcore-wotlk/commit/0a9202a82954e9458707e6e4c2b5370fb7d6a7ae it is now possible to lower prioritize other scripts via additional arguments to "AC_ADD_SCRIPT_LOADER". This is now done using the additional argument "SC_Npc_VisualWeapon" which ensures that the mod-transmog gains a higher priority than mod-weapon-visual.
Tested build on Ubuntu 16.04 using clang7; tested successfully in-game with both modules installed.
> feat(PlayerScript): Ensure compatibility with mod-weapon-visual

- data/sql/db-world/trasm_world_texts.sql
- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
https://github.com/azerothcore/azerothcore-wotlk/pull/2454
> followup #2454

- conf/transmog.conf.dist
- data/sql/db-characters/trasmorg.sql
- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
This PR is implement a Appearance Collection system like later expansions. When an item is equipped or a quest is completed, data is saved to the account. Players can use any of the items they have collected as a transmog candidate, rather than only items in the bag. If this is disabled through config option, behavior will be the same as before and require items in bag to be transmog.
Because players will now have many more items available for transmog, I have also implemented paging in the gossip menu so that they can browse through many items.
I have created a client addon that can track which item still need to have appearance collected and show tooltip:
I also have modified version of MogIt that can show collected appearance:
Note that these addons still need to manually sync data …
> Appearance Collection

- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
This will greatly improve collection system performance by making fewer DB calls. It will also avoid SQL errors caused by async DB inserts sometimes arriving at the same time.
This PR will also prevent adding items to the Appearance collection when the BoP Tradable or Refundable flags are set. Once these timers expire or are removed through using the item, it can be added to the collection. This prevents many players trading or refunding items to get free appearances.
closes #73
Partially resolves https://github.com/azerothcore/mod-transmog/issues/77
> Implement Appearance Collection Cache

- conf/transmog.conf.dist
- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
Adds option that players can set item to "invisible" transmog. This can be disabled through the config.
Note that because items that have been transmog use the icon of the transmog source in the equipment UI frame, this means that items transmog to hidden will appear as empty item slot in equipment frame. The correct icon appears elsewhere, so I think this shouldn't be a problem.
Closes https://github.com/azerothcore/mod-transmog/issues/42.
> Implement Hidden Transmog option

- conf/transmog.conf.dist
- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
This PR aims to address the discussion on ChromieCraft: https://github.com/chromiecraft/chromiecraft/discussions/3537
Currently the behavior is that the item doesn't get added to the appearance collection until it becomes soulbound, such as by enchanting it or running out the two hour grace period during an instance. This PR maintains that behavior by default, though I'm not sure what the alternative behavior should be, nor how to accomplish it, as I'm very unfamiliar with the way this module works.
Currently untested, but has no build errors, very open to feedback.
> Add config option to allow adding tradeable/refundable items to appearance collection.

- conf/transmog.conf.dist
- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
Added the ability to let Transmog system check for quests that were completed before transmog was added or while it was disabled, and add these rewards to the players' appearance collection. Each player is flagged after this check is run so that it will only happen once and prevent unnecessary checking; the flags can all be cleared by setting ResetRetroActiveAppearancesFlag to 1 in the config.
> Implement retroactive quest appearance collection

- src/transmog_scripts.cpp
This will fix the Retroactive Appearance collection check to work correctly.
Please note that the flag in mog-transmog will need to be reset for all players so that the check runs for them again.
Sorry for not catch this in my earlier testing!
> Correctly check rewarded quests instead of completed quests

- src/transmog_scripts.cpp
Use getRewardedQuests instead of a DB call.
Thanks Nefertum for the suggestion!
> Performance optimization in retroactive appearances check

- src/Transmogrification.cpp
- src/Transmogrification.h
- src/cs_transmog.cpp
- src/transmog_scripts.cpp
These items will continue to be add to the collection in case someone wants to remember that the player has collected these equipment, but the Appearance Collected message will never show to players because there is no appearance for these items.
> Do not show Appearance Added message for items that cannot ever be transmogged

- src/transmog_scripts.cpp
Avoids a crash if a player has invalid item ID stored as a collected appearance (changed or removed custom item, data corruption, etc. could cause this to happen.) Invalid item IDs are now only skipped instead.
Closes https://github.com/azerothcore/mod-transmog/issues/96
> Crash fix when invalid item in collection database

- data/sql/db-world/trasm_world_texts.sql
- src/Transmogrification.h
- src/cs_transmog.cpp
This allows the latest version of https://github.com/ZhengPeiRu21/transmog-addons to sync appearances with the server when the command is run. This also could be useful for any other addon that would like to track collected appearances, so it is not only used by this addon.
> Add support for add-on sync command

- src/transmog_scripts.cpp
Closes https://github.com/azerothcore/mod-transmog/issues/100.
> Fix crash when performing RetroActive appearance check with invalid quest IDs

- data/sql/db-world/trasm_world_texts.sql
Currently players need to be GM to sync appearances. This makes the command correctly available to players.
> fix: Correct access level required for sync command

- conf/transmog.conf.dist
- src/Transmogrification.cpp
- src/Transmogrification.h
Correctly do allow Main-hand Weapons and Off-hand Weapons to only be allowed to transmog to weapons of the same inventory type.
> feat: Implement multiple AllowMixedWeaponType options

- src/transmog_scripts.cpp
Found this bug when testing out a new module: https://github.com/noisiver/mod-junk-to-gold
`junk-to-gold` also uses the `OnLootItem` function and was being called BEFORE `transmog`. By the time `transmog` gets to the item, the item is already gone.
This type check ensures that the pointer still points to an item. If not, it must have been deleted by `junk-to-gold` or any other module that might delete an item when `OnLootItem` is triggered.
I am unsure if `!item` is still needed or not. It appears that it passes even when the pointer doesn't point to anything useful.
> (bug) Adds check to OnLootItem() to ensure that the pointer is still valid

- src/transmog_scripts.cpp
checking this crash log https://gist.github.com/assada/068435b470644a1b9a98d94b61a056d3
it seems that the `target` variable is `0x0` as value, this could make the crash but I am not sure 100%, so please, test this PR.
closes https://github.com/azerothcore/mod-transmog/issues/112
closes https://github.com/azerothcore/mod-transmog/issues/135
> fix: add null-check for target var in transmog_scripts.cpp

- src/transmog_scripts.cpp
This PR uses the new hooks introduced here - https://github.com/azerothcore/azerothcore-wotlk/pull/18637.
> Use new unit hooks to optimize BuildValuesUpdate

- conf/transmog.conf.dist
- src/Transmogrification.cpp
- src/Transmogrification.h
- Refactor of InvType and Subclass mismatch handling to allow for easier future extensibility
- (Transmogrification.AllowLowerTiers) Add the ability to transmog into any tiered armor class the user can actually equip (e.g. Plate users can use all tiers, so can transmog into items from any tier, leather users can only use leather and cloth so can tmog into leather and cloth, etc.)
- (Transmogrification.AllowMixedOffhandArmorTypes) Add the ability to transmog offhand armor types into any other offhand armor type (e.g. "Held in Off-hand" gear over shields and vice versa)
- Allow MISC-subclass armor to be transmogrified over any armor tier as long as their types match (Helm and Helm, etc) 
- Fixes #147 
- Tested default config - works as expected
- Tested AllowLowerTiers by itself - works as …
> Code Cleanup, More Options and a Bugfix.

- src/Transmogrification.cpp
I somehow missed in my previous MR that an exception was missing for One-Hand -> Main Hand/Main Hand -> One-Hand etc. 
This MR allows One Hand (handedness agnostic) weapons to be transmogged by Main Hand weapons (and Off-Hand weapons if LOOSE mixed weapon type), and Main Hand/Off Hand weapons to be transmogged by One Hand weapons.
Fixes #159
> Fixed a bug with One-Hand transmogging

- conf/transmog.conf.dist
- data/sql/db-world/trasm_world_VendorItems.sql
- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
- Refactored several bits of transmog interface handling
- Unified gossip menu logic for old bag-based system and new collection-based system (means the old bag-based system now has access to search features, etc and the code is overall simpler.)
- Fixed several bugs that arose from the old bag-based system not being actively maintained
- Fixed a bug with the gossip menu system where clicking into slots with no available items or no item equipped would hang the gossip menu
- General code cleanup in transmog_scripts.cpp
- (Transmogrification.UseVendorInterface - Disabled by default) Adds the ability to use a mock vendor interface instead of the gossip menu so that item previews can be used. 
Comes with its own limitations, namely:
- Placeholder items had to be used to fill the role of the …
> Vendor Interface and Code Cleanup

- src/Transmogrification.cpp
I introduced a regression in a previous MR causing weapon InvType mismatch to not properly respect the fact that Loose means all bets are off and we let any weapon tmog over any weapon.
Closes #168
> Fix an issue with MixedWeaponType:LOOSE 2h->1h tmog

- conf/transmog.conf.dist
- src/Transmogrification.cpp
- src/transmog_scripts.cpp
closes https://github.com/azerothcore/mod-transmog/issues/133
I tested it in-game with few items
> feat: add sorting feature and related conf

- src/transmog_scripts.cpp
azerothcore/azerothcore-wotlk#21020
> Update transmog_scripts.cpp - fix build

- src/Transmogrification.cpp
- src/cs_transmog.cpp
Added Game Master override for plus feature eligibility and enhanced error handling in the portable transmogrification NPC command. Now checks for feature enablement, player eligibility, and spell availability before casting.
> Improve eligibility checks for portable transmog NPC
