azerothcore/mod-transmog

- src/Transmogrification.cpp
See this:
https://github.com/azerothcore/mod-transmog/pull/7#discussion_r171092453
> Fix double cost thanks to Deku

- src/Transmogrification.cpp
No testing necessary, just fix the dangling else.
> Fix: dangling else

- src/Transmogrification.h
Fixed build errors after this PR got merged https://github.com/azerothcore/azerothcore-wotlk/pull/1627
> Compatibility issues fix

- README.md
- src/transmog_scripts.cpp
adapt to this commit:
https://github.com/azerothcore/azerothcore-wotlk/commit/b6cb9247ba96a862ee274c0765004e6d2e66e9e4
Tested in-game and build on Ubuntu 16.04, clang 7
> feat: replace old gossip macros

- CMakeLists.txt
- src/transmog_scripts.cpp
- Delete useless config loading. This module supports CMake macros `AC_ADD_CONFIG_FILE`
> fix(Config): del useless loading config

- src/transmog_scripts.cpp
Very small changes to improve the english (from my point of view)
Note: i just realized the previous form was just non-interrogative but it looked like it was broken and missing a "?"
> style(cpp): Improve english texts

- conf/transmog.conf.dist
- Never implemented
- Closes https://github.com/azerothcore/mod-transmog/issues/33#issuecomment-586684770
> refactor(conf): Remove unused conf option

- README.md
Found some directions were missing from the readme. This is to update the readme with the additional directions.
> Update readme with missing directions

- .github/workflows/core_build.yml
- Part https://github.com/azerothcore/azerothcore-wotlk/pull/5671
> feat(CI): set only default version clang

- src/Transmogrification.cpp
- src/Transmogrification.h
- src/transmog_scripts.cpp
- Add support new db api
- Delete ace inherited
> chore(Misc): add support new db api

- data/sql/db-world/trasm_world_NPC.sql
Remove Inhabit Type for upcoming PR to remove Inhabit Type
> Remove Inhabit Type for upcoming PR

- src/Transmogrification.cpp
https://github.com/azerothcore/azerothcore-wotlk/pull/10366
> feat(Logging): add support new logging

- src/Transmogrification.cpp
- src/transmog_scripts.cpp
https://github.com/azerothcore/azerothcore-wotlk/pull/10211
> feat(DBLayer): add support new db api

- src/Transmogrification.h
- src/transmog_scripts.cpp
Allows players to search for appearances
> Implement Search feature for transmogs

- src/Transmogrification.cpp
- src/transmog_scripts.cpp
Closes https://github.com/chromiecraft/chromiecraft/issues/4004
> fix: Support saving hidden items as part of transmog sets

- conf/transmog.conf.dist
Added the Missing line to the config.dist
> fix(config): Missing entry

- conf/transmog.conf.dist
- data/sql/db-world/trasm_world_texts.sql
- src/Transmogrification.cpp
- src/Transmogrification.h
- src/cs_transmog.cpp
having the right subscription a player can use the command `.transmog portable` now, if the player has not the subscription the only way to use `.transmog portable` is having the security level `SEC_MODERATOR` as before
> feat: transmog plus pet

- src/transmog_scripts.cpp
This fixes a previous committed fix relating to the added appearance message.
> Fix to the fix of added appearance message

- src/Transmogrification.cpp
- src/Transmogrification.h
- src/cs_transmog.cpp
Apply some DRY principle
Clean up code
Fix transmog plus configs not reloading on .reload config
> refactor: Improve Transmog Plus code

- conf/transmog.conf.dist
- src/Transmogrification.cpp
- src/Transmogrification.h
Allow subscribers to skip level requirements when checking for transmog requirements.
> feat: TransmogPlus - Skip Level Req

- README.md
> Updated readme to notify about the newer change and updated the build badge to work properly
